runtime: python312

instance_class: F1

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

entrypoint: flask run --host=0.0.0.0 --port=$PORT

env_variables:
  FLASK_ENV: "production"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 1